/**
 * COCO 80-class dataset label map used by YOLOv8n. Index = class id.
 *
 * Source: Ultralytics COCO dataset. Keep in sync when swapping in YOLO11 /
 * other variants that share the same COCO label space.
 */
export const COCO_CLASSES: string[] = [
  "person",
  "bicycle",
  "car",
  "motorcycle",
  "airplane",
  "bus",
  "train",
  "truck",
  "boat",
  "traffic light",
  "fire hydrant",
  "stop sign",
  "parking meter",
  "bench",
  "bird",
  "cat",
  "dog",
  "horse",
  "sheep",
  "cow",
  "elephant",
  "bear",
  "zebra",
  "giraffe",
  "backpack",
  "umbrella",
  "handbag",
  "tie",
  "suitcase",
  "frisbee",
  "skis",
  "snowboard",
  "sports ball",
  "kite",
  "baseball bat",
  "baseball glove",
  "skateboard",
  "surfboard",
  "tennis racket",
  "bottle",
  "wine glass",
  "cup",
  "fork",
  "knife",
  "spoon",
  "bowl",
  "banana",
  "apple",
  "sandwich",
  "orange",
  "broccoli",
  "carrot",
  "hot dog",
  "pizza",
  "donut",
  "cake",
  "chair",
  "couch",
  "potted plant",
  "bed",
  "dining table",
  "toilet",
  "tv",
  "laptop",
  "mouse",
  "remote",
  "keyboard",
  "cell phone",
  "microwave",
  "oven",
  "toaster",
  "sink",
  "refrigerator",
  "book",
  "clock",
  "vase",
  "scissors",
  "teddy bear",
  "hair drier",
  "toothbrush",
];

/** Small/manual objects that need the high-resolution ROI pass to be reliable. */
export const SMALL_OBJECT_CLASSES: Set<string> = new Set([
  "cell phone",
  "bottle",
  "cup",
  "book",
  "remote",
  "mouse",
  "keyboard",
  "scissors",
  "fork",
  "knife",
  "spoon",
  "toothbrush",
  "clock",
  "wine glass",
  "vase",
]);

export function className(classId: number): string {
  return COCO_CLASSES[classId] ?? "unknown";
}
